RMDIR "FNA\bin" /S /Q
RMDIR "FNA\obj" /S /Q
RMDIR "Nez\Nez.Persistence\bin" /S /Q
RMDIR "Nez\Nez.Persistence\obj" /S /Q
RMDIR "Nez\Nez.Portable\bin" /S /Q
RMDIR "Nez\Nez.Portable\obj" /S /Q
RMDIR "Nez\Nez.ImGui\bin" /S /Q
RMDIR "Nez\Nez.ImGui\obj" /S /Q
RMDIR "PitHero\bin" /S /Q
RMDIR "PitHero\obj" /S /Q
