namespace RolePlayingFramework.Equipment
{
    /// <summary>Item categories for restrictions and effects.</summary>
    public enum ItemKind
    {
        Consumable,
        WeaponSword,
        WeaponKnuckle,
        WeaponStaff,
        WeaponRod,
        WeaponDagger,
        WeaponBow,
        WeaponAxe,
        WeaponFist,
        WeaponClaw,
        ArmorMail,
        ArmorGi,
        ArmorRobe,
        ArmorMedium,
        ArmorLight,
        ArmorHeavy,
        HatHelm,
        HatHeadband,
        HatWizard,
        HatPriest,
        Shield,
        Accessory,
        AccessoryBoots,
        AccessoryGloves,
        AccessoryRing,
        OrbFire,
        OrbWater,
        OrbEarth,
        OrbWind,
        OrbLight,
        OrbDark,
        OrbNeutral
    }
}
