namespace PitHero.Util.SoundEffectTypes
{
    public enum SoundEffectType
    {
        Jump,
        Land,
        Restorative,
        Punch,
        ChestOpen,
        SwordSlash,
        TakeDamage,
        EnemyDefeat,
        PayGold,
        ItemPurchase,
        ItemSell,
        PickCrop,
        StoreCrop,
        RetrieveCrop,
        TopBarButtonClick,
        TabButtonClick,
        CancelButtonClick,
        NormalButtonClick,
        FoodReady,
        TicketPosted,
        TakeOrder,
        PartyFinishedEating,
        Digging,
        Watering,
        PlaceFoodOnTable,
        DropEmptyDish
    }
}
